server:
  port: 6125
spring:
  application:
    name: lychnos


jdevelops:
  swagger:
    base-package:
      - cn.tannn.lychnos.controller
    author: tan
    version: 0.0.1
    group-name: lychnos
    display-name: Lychnos
    description: Lychnos
    email: 1445763190@qq.com
    title: lychnos

knife4j:
  enable: true
  setting:
    language: zh-CN
    custom-code: 500
    enable-footer-custom: false
    enable-dynamic-parameter: true

# ??
management:
  endpoints:
    # ????????
    #    enabled-by-default: false
    web:
      #      discovery:
      #        enabled: false #????????
      exposure:
        include:
          - info # prometheus
          - health
        exclude:
          - shutdown
          - sessions
          - beans
          - env
  metrics:
    tags:
      application: ${spring.application.name}
