server:
  port: 6125
spring:
  profiles:
    active: ${CONFIG_ENV:dev}
  application:
    name: lychnos
  servlet:
    multipart:
      enabled: true
      max-file-size:  ${FILE_MAX_SIZE:100MB}
      max-request-size: ${FILE_MAX_SIZE:100MB}

jdevelops:
  swagger:
    base-package:
      - cn.tannn.lychnos.controller
    author: tan
    version: 0.0.1
    group-name: lychnos
    display-name: Lychnos
    description: Lychnos
    email: 1445763190@qq.com
    title: lychnos
  jwt:
    token-secret: b40715ff972d60c4yff8044acfb33ba091544b2e21825672edc38799f52f1895
    web:
      interceptor:
        exclude-path-patterns:
          - /login
          - /error
          - /logout
    verify-platform: true

knife4j:
  enable: true
  setting:
    language: zh-CN
    custom-code: 500
    enable-footer-custom: false
    enable-dynamic-parameter: true
